#pragma once

struct alignas(16) ExplosionDamagerBlastParams
{
    void* VTable;              // 0x00
    uint8_t Unknown08[0x20];   // 0x08

    float Damage;              // 0x28
    float Radius;              // 0x2C
    float Unknown30;           // 0x30
    float Force;               // 0x34
    Vector3 Position;          // 0x38

    uint8_t Unknown44[0x64];   // 0x44
    Vector3 BoundsMin;         // 0xA8, generated by the game
    Vector3 BoundsMax;         // 0xB4, generated by the game
    uint8_t UnknownC0[0x10];   // 0xC0

    int32_t ExplosionType;     // 0xD0
    uint8_t Enabled;           // 0xD4
    uint8_t UnknownD5[3];      // 0xD5
    uint64_t UnknownD8;        // 0xD8
    uint32_t DamageType;       // 0xE0
    uint8_t UnknownE4[0x0C];   // 0xE4
};
